# Generated by Django 5.1.3 on 2024-12-28 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0002_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('rodado', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BicycleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bicycle_images/')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bicicletas.bicycle')),
            ],
        ),
    ]
